# tasks/main.yml

- name: Install pip packages
  pip:
    name:
      - requests==2.31.0
      - docker-compose
      - docker<7.0

- name: Clone the repository
  git:
    repo: "{{ git_repository }}"
    dest: "{{ deployment_path }}"
    version: "{{ git_branch }}"
    force: yes

- name: Run docker-compose
  docker_compose:
    project_src: "{{ deployment_path }}"
    build: yes
